# -*- coding: utf-8 -*-
"""Trabalho final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nD8MufOq37PBf-Wg2BxYcXR3E1kd_nJH
"""

#importação da biblioteca PANDAS e dos arquivos

import pandas as pd
import numpy as np
pd.set_option("max_columns", None)
pd.set_option("max_rows", None)
df_detail = pd.read_excel('detalhamento_m4u.xlsx')	#- importando o arquivo "detalhamento_m4u.xlsx".                                                                                                               
df_sap = pd.read_csv('mcg3.csv', sep='|')		#- importando o arquivo "mcg3.csv".

#alterando o nome das colunas
df_detail.rename(columns=df_detail.iloc[0], inplace=True)
df_detail = df_detail.drop(index=0)
df_detail = df_detail.rename(columns={'Vlookup Bruto':'Valor bruto'})

#colocando em caixa alta
df_detail['Operadora'] = df_detail['Operadora'].str.upper()

#convertendo valores da coluna 'Valor bruto' e 'Escritório de vendas', do ddf_detail

df_detail['Valor bruto'] = pd.to_numeric(df_detail['Valor bruto'], downcast='float')
df_detail['Escritório de vendas'] = pd.to_numeric(df_detail['Escritório de vendas']
                                                  , downcast='signed')

df_detail.drop(columns=['UF'], inplace=True)

#trocando valor 'TNL' por 'OI' e mudando o nome da coluna 'Fornecedor', para 'Operadora'
df_sap.loc[(df_sap.Fornecedor == 'TNL'), 'Fornecedor']='OI'

# Somando os valores da coluna 'Val.líq.', 
# em função do agrupamento de 'Escritório' e 'Fornecedor

df_sap = df_sap.groupby(['Escritório de vendas', 'Fornecedor'])['Val.líq.'].sum()
df_sap = pd.DataFrame(df_sap)
df_sap = df_sap.rename(columns={'Fornecedor':'Operadora'})

df_sap = df_sap.reset_index()

df_sap = df_sap.drop_duplicates()
df_detail = df_detail.drop_duplicates()
df_detail.rename(columns={'Operadora':'Fornecedor'}, inplace=True)

df_final=pd.merge(df_sap, df_detail, on=['Escritório de vendas', 'Fornecedor'] ,how='outer')

df_final.at[141, 'NomeFantasia'] = 'BEMOL FARMA PRESIDENTE FIGUEIREDO'

df_final['NomeFantasia'].fillna(value='Não cadastrada', inplace=True)
df_final['Valor bruto'].fillna(value=0.00, inplace=True)

df_final = df_final[['NomeFantasia','Fornecedor','Val.líq.','Valor bruto', 
                     'Escritório de vendas']]

df_final.rename(columns={'NomeFantasia':'Loja', 'Fornecedor':'Operadora', 
                         'Val.líq.':'Valor líquido'}, inplace=True)
df_final.drop(columns='Escritório de vendas', inplace=True)

def status(x, y):
  return np.where(df_final['Valor líquido']==df_final['Valor bruto'],
                               'Valores em conformidade', 
                               'ERRO!')

df_final['status'] = status(df_final['Valor líquido'], df_final['Valor bruto'])

df_final

df_final.to_csv(r'C:\Desafio_DF_final.csv',index=False)

